[2025-03-10T13:34:13.543+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.import_csv manual__2025-03-10T13:34:12.284681+00:00 [queued]>
[2025-03-10T13:34:13.553+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.import_csv manual__2025-03-10T13:34:12.284681+00:00 [queued]>
[2025-03-10T13:34:13.554+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T13:34:13.554+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-10T13:34:13.554+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T13:34:13.570+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): import_csv> on 2025-03-10 13:34:12.284681+00:00
[2025-03-10T13:34:13.577+0000] {standard_task_runner.py:55} INFO - Started process 921 to run task
[2025-03-10T13:34:13.581+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'import_csv', 'manual__2025-03-10T13:34:12.284681+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmp4dvxmjg6']
[2025-03-10T13:34:13.582+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask import_csv
[2025-03-10T13:34:13.664+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.import_csv manual__2025-03-10T13:34:12.284681+00:00 [running]> on host d234808dccbd
[2025-03-10T13:34:13.737+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=import_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T13:34:12.284681+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T13:34:12.284681+00:00
[2025-03-10T13:34:13.738+0000] {sql.py:254} INFO - Executing: 
        COPY staging_hr FROM '/home/dg/hr.data1.csv' 
        DELIMITER ',' CSV HEADER;
        
[2025-03-10T13:34:13.746+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T13:34:13.992+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T13:34:14.048+0000] {sql.py:375} INFO - Running statement: 
        COPY staging_hr FROM '/home/dg/hr.data1.csv' 
        DELIMITER ',' CSV HEADER;
        , parameters: None
[2025-03-10T13:34:14.065+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "staging_hr" does not exist

[2025-03-10T13:34:14.075+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=import_csv, execution_date=20250310T133412, start_date=20250310T133413, end_date=20250310T133414
[2025-03-10T13:34:14.086+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task import_csv (relation "staging_hr" does not exist
; 921)
[2025-03-10T13:34:14.116+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-10T13:34:14.137+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
