[2025-03-10T19:55:10.876+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_update_department manual__2025-03-10T19:55:07.589200+00:00 [queued]>
[2025-03-10T19:55:10.898+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_update_department manual__2025-03-10T19:55:07.589200+00:00 [queued]>
[2025-03-10T19:55:10.898+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T19:55:10.899+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-10T19:55:10.899+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T19:55:10.922+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_update_department> on 2025-03-10 19:55:07.589200+00:00
[2025-03-10T19:55:10.929+0000] {standard_task_runner.py:55} INFO - Started process 7278 to run task
[2025-03-10T19:55:10.939+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'insert_update_department', 'manual__2025-03-10T19:55:07.589200+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmpgxao30ad']
[2025-03-10T19:55:10.939+0000] {standard_task_runner.py:83} INFO - Job 146: Subtask insert_update_department
[2025-03-10T19:55:11.039+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.insert_update_department manual__2025-03-10T19:55:07.589200+00:00 [running]> on host f1d7771c7032
[2025-03-10T19:55:11.126+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=insert_update_department
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T19:55:07.589200+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T19:55:07.589200+00:00
[2025-03-10T19:55:11.127+0000] {sql.py:254} INFO - Executing: CALL update_department();
[2025-03-10T19:55:11.142+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T19:55:11.408+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T19:55:11.435+0000] {sql.py:375} INFO - Running statement: CALL update_department();, parameters: None
[2025-03-10T19:55:11.448+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.NotNullViolation: null value in column "department_id" of relation "department" violates not-null constraint
DETAIL:  Failing row contains (null, Sales).
CONTEXT:  SQL statement "INSERT INTO department (department_id, Department)
SELECT s.department_id, s.Department
FROM staging_hr s
LEFT JOIN department d ON s.department_id = d.department_id WHERE d.department_id IS NULL"
PL/pgSQL function update_department() line 3 at SQL statement

[2025-03-10T19:55:11.459+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=insert_update_department, execution_date=20250310T195507, start_date=20250310T195510, end_date=20250310T195511
[2025-03-10T19:55:11.471+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 146 for task insert_update_department (null value in column "department_id" of relation "department" violates not-null constraint
DETAIL:  Failing row contains (null, Sales).
CONTEXT:  SQL statement "INSERT INTO department (department_id, Department)
SELECT s.department_id, s.Department
FROM staging_hr s
LEFT JOIN department d ON s.department_id = d.department_id WHERE d.department_id IS NULL"
PL/pgSQL function update_department() line 3 at SQL statement
; 7278)
[2025-03-10T19:55:11.509+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-10T19:55:11.530+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
