[2025-03-11T19:12:54.706+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_employees manual__2025-03-11T19:12:50.563766+00:00 [queued]>
[2025-03-11T19:12:54.714+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_employees manual__2025-03-11T19:12:50.563766+00:00 [queued]>
[2025-03-11T19:12:54.714+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T19:12:54.715+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T19:12:54.715+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T19:12:54.727+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_employees> on 2025-03-11 19:12:50.563766+00:00
[2025-03-11T19:12:54.732+0000] {standard_task_runner.py:55} INFO - Started process 124 to run task
[2025-03-11T19:12:54.734+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'insert_employees', 'manual__2025-03-11T19:12:50.563766+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmpep1gqv_1']
[2025-03-11T19:12:54.735+0000] {standard_task_runner.py:83} INFO - Job 343: Subtask insert_employees
[2025-03-11T19:12:54.793+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.insert_employees manual__2025-03-11T19:12:50.563766+00:00 [running]> on host ea6da4397df7
[2025-03-11T19:12:54.859+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=insert_employees
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T19:12:50.563766+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T19:12:50.563766+00:00
[2025-03-11T19:12:54.860+0000] {sql.py:254} INFO - Executing: CALL update_employees();
[2025-03-11T19:12:54.869+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-11T19:12:55.059+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-11T19:12:55.083+0000] {sql.py:375} INFO - Running statement: CALL update_employees();, parameters: None
[2025-03-11T19:12:55.110+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=project2, task_id=insert_employees, execution_date=20250311T191250, start_date=20250311T191254, end_date=20250311T191255
[2025-03-11T19:12:55.147+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-03-11T19:12:55.175+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
