[2025-03-10T23:25:03.473+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.import_csv manual__2025-03-10T23:25:02.221922+00:00 [queued]>
[2025-03-10T23:25:03.482+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.import_csv manual__2025-03-10T23:25:02.221922+00:00 [queued]>
[2025-03-10T23:25:03.483+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T23:25:03.483+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-10T23:25:03.483+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T23:25:03.495+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): import_csv> on 2025-03-10 23:25:02.221922+00:00
[2025-03-10T23:25:03.500+0000] {standard_task_runner.py:55} INFO - Started process 127 to run task
[2025-03-10T23:25:03.502+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'import_csv', 'manual__2025-03-10T23:25:02.221922+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmpaz2l2f43']
[2025-03-10T23:25:03.503+0000] {standard_task_runner.py:83} INFO - Job 179: Subtask import_csv
[2025-03-10T23:25:03.573+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.import_csv manual__2025-03-10T23:25:02.221922+00:00 [running]> on host 9670e20211e7
[2025-03-10T23:25:03.633+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=import_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T23:25:02.221922+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T23:25:02.221922+00:00
[2025-03-10T23:25:03.634+0000] {sql.py:254} INFO - Executing: 
        COPY staging_hr FROM '/tmp/hr_data.csv'
        DELIMITER ',' CSV HEADER;
        
[2025-03-10T23:25:03.647+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T23:25:03.892+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T23:25:03.920+0000] {sql.py:375} INFO - Running statement: 
        COPY staging_hr FROM '/tmp/hr_data.csv'
        DELIMITER ',' CSV HEADER;
        , parameters: None
[2025-03-10T23:25:03.926+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY staging_hr, line 2: "0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,..."

[2025-03-10T23:25:03.936+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=import_csv, execution_date=20250310T232502, start_date=20250310T232503, end_date=20250310T232503
[2025-03-10T23:25:03.948+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 179 for task import_csv (extra data after last expected column
CONTEXT:  COPY staging_hr, line 2: "0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,..."
; 127)
[2025-03-10T23:25:03.996+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-10T23:25:04.023+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
