[2025-03-11T22:43:10.163+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_employees manual__2025-03-11T22:43:06.290643+00:00 [queued]>
[2025-03-11T22:43:10.171+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.insert_employees manual__2025-03-11T22:43:06.290643+00:00 [queued]>
[2025-03-11T22:43:10.172+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T22:43:10.172+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T22:43:10.172+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T22:43:10.184+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_employees> on 2025-03-11 22:43:06.290643+00:00
[2025-03-11T22:43:10.188+0000] {standard_task_runner.py:55} INFO - Started process 244 to run task
[2025-03-11T22:43:10.190+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'insert_employees', 'manual__2025-03-11T22:43:06.290643+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmp_y6hhvje']
[2025-03-11T22:43:10.191+0000] {standard_task_runner.py:83} INFO - Job 356: Subtask insert_employees
[2025-03-11T22:43:10.246+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.insert_employees manual__2025-03-11T22:43:06.290643+00:00 [running]> on host 4ee7518c3f18
[2025-03-11T22:43:10.308+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=insert_employees
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T22:43:06.290643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T22:43:06.290643+00:00
[2025-03-11T22:43:10.309+0000] {sql.py:254} INFO - Executing: CALL update_employees();
[2025-03-11T22:43:10.317+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-11T22:43:10.509+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-11T22:43:10.533+0000] {sql.py:375} INFO - Running statement: CALL update_employees();, parameters: None
[2025-03-11T22:43:10.559+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=project2, task_id=insert_employees, execution_date=20250311T224306, start_date=20250311T224310, end_date=20250311T224310
[2025-03-11T22:43:10.604+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-03-11T22:43:10.632+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
